services:
  frontend:
    image: devmhimran/taskbit:v1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: ./package.json
          action: rebuild
        - path: ./yarn.lock
          action: rebuild
        - path: .
          target: /app
          action: sync
    environment:
      - DATABASE_URL=${DATABASE_URL}

      - NEXT_PUBLIC_JWT_ACCESS_SECRET=${NEXT_PUBLIC_JWT_ACCESS_SECRET}
      - NEXT_PUBLIC_JWT_REFRESH_SECRET=${NEXT_PUBLIC_JWT_REFRESH_SECRET}
      - NEXT_PUBLIC_AUTH_SECRET=${NEXT_PUBLIC_AUTH_SECRET}

      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - APP_BASE_URL=${APP_BASE_URL}

      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    depends_on:
      - db

  studio:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "yarn prisma generate && yarn prisma studio"
    ports:
      - '5555:5555'
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
